### ISSUE TITLE
Extension working with Windows 10 Remote WSL Connection

### ISSUE THREAD

**Issue by ldemidov** [elixir-lsp/vscode-elixir-ls#134]
Trying to use the extension with the starter Phoenix demo app.  Syntax Highlighting is fine but none of the language server features work.

### Environment

Debug Info:
```
- Elixir & Erlang versions (elixir --version):
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.10.4 (compiled with Erlang/OTP 22)
  * VSCode ElixirLS version: 0.5.0
  * Operating System Version: linux 4.19.104-microsoft-standard
```
  
VSCode is running in Windows 10 2004
Remote Connection to Ubuntu 20 running WSL2

###Output Log:
The ElixirLS server crashed 5 times in the last 3 minutes. The server will not be restarted.

```[Warn  - 9:52:56 PM] ** (MatchError) no match of right hand side value: {:error, {:dialyzer, {'no such file or directory', 'dialyzer.app'}}}
    (language_server 0.5.0) lib/language_server/cli.ex:9: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
[Info  - 9:52:56 PM] Connection to server got closed. Server will restart.
[Warn  - 9:52:57 PM] ** (MatchError) no match of right hand side value: {:error, {:dialyzer, {'no such file or directory', 'dialyzer.app'}}}
    (language_server 0.5.0) lib/language_server/cli.ex:9: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
[Info  - 9:52:57 PM] Connection to server got closed. Server will restart.
[Warn  - 9:52:57 PM] ** (MatchError) no match of right hand side value: {:error, {:dialyzer, {'no such file or directory', 'dialyzer.app'}}}
    (language_server 0.5.0) lib/language_server/cli.ex:9: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
[Info  - 9:52:57 PM] Connection to server got closed. Server will restart.
[Warn  - 9:52:57 PM] ** (MatchError) no match of right hand side value: {:error, {:dialyzer, {'no such file or directory', 'dialyzer.app'}}}
    (language_server 0.5.0) lib/language_server/cli.ex:9: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
[Info  - 9:52:57 PM] Connection to server got closed. Server will restart.
[Warn  - 9:52:57 PM] ** (MatchError) no match of right hand side value: {:error, {:dialyzer, {'no such file or directory', 'dialyzer.app'}}}
    (language_server 0.5.0) lib/language_server/cli.ex:9: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
[Error - 9:52:57 PM] Connection to server got closed. Server will not be restarted.
```

### Troubleshooting

- [X] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [ ] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

Tried restarting.  Not seeing the .elixir_ls directory in my workspace.

**Comment by ldemidov** [comment]
I got it working.  The problem seems to be Ubuntu doesn't fully install Erlang/Dialyzer when installing Elixir.  Doing apt install erlang fix the issue.  My bad for the newb mistake.  

The vscode extension works great now.  Thanks for making it!

**Comment by axelson** [comment]
Okay, thanks for the info!
