### ISSUE TITLE
Compiler error and @spec suggestion not working

### ISSUE THREAD

**Issue by shanlalit** [elixir-lsp/vscode-elixir-ls#33]
**Elixir Version:**
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.9.4 (compiled with Erlang/OTP 20)

**Extension version:** 0.2.28 (I've also tried downgrading)
Had same issue with Elixir 1.10.0 also.

VSCode(Stable latest release) has stopped showing compile error (underline highlights and error message) and @spec suggestions. They used work fine but I don't remember exactly when, for user it was with Elixir 1.9.4.

What all I have tried:
- I was running Elixir 1.10.0 on ubunut, installed asdf to downgrade to 1.9.4
- I have tried removing and regenerating the .elixirls, deps, and build folders
- PLTs were generated again
- Vim coc-elixir is working fine without any customization 

Here is my mix file:
```elixir
defmodule MyProject.MixProject do
  @moduledoc """
   Example:
  """
  use Mix.Project

  def project do
    [
      app: :my_project,
      version: "0.1.0",
      elixir: "~> 1.8",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
      {:earmark, "~> 1.4", only: :dev},
      {:ex_doc, "~> 0.19", only: :dev},
      {:dialyxir, "~> 1.0.0-rc.7", only: [:dev, :test], runtime: false},
      {:credo, "~> 1.1.0", only: [:dev, :test], runtime: false}
    ]
  end
end
```
Here is the fresh ElixirLS log on cold start with the project in VSCode stable version.

> Compiling with Mix env test
> [Info  - 12:30:54 PM] Compile took 61 milliseconds
> [Info  - 12:30:54 PM] [ElixirLS Dialyzer] Checking for stale beam files
> [Info  - 12:30:55 PM] [ElixirLS Dialyzer] Analyzing 0 modules: []
> [Info  - 12:30:55 PM] [ElixirLS Dialyzer] Analysis finished in 12 milliseconds
> [Info  - 12:30:55 PM] Dialyzer analysis is up to date
> [Info  - 12:30:56 PM] [ElixirLS Dialyzer] Writing manifest...
> [Info  - 12:31:00 PM] [ElixirLS Dialyzer] Done writing manifest.
> [Error - 12:31:13 PM] Request textDocument/documentSymbol failed.
>   Message: an exception was raised:
>     ** (SyntaxError) nofile:14: unexpected token: end
>         (language_server) lib/language_server/providers/document_symbols.ex:41: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
>         (language_server) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/2
>         (language_server) lib/language_server/server.ex:442: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
>   Code: -32000 
> 
> 12:31:13.192 [error] Process #PID<0.1356.0> raised an exception
> ** (SyntaxError) nofile:14: unexpected token: end
>     (language_server) lib/language_server/providers/document_symbols.ex:41: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
>     (language_server) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/2
>     (language_server) lib/language_server/server.ex:442: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
>

**Comment by shanlalit** [comment]
Resolved, I was expecting compilation error and @spec suggestions on  a .exs file. According to ElixirLS README:

> In order to debug modules in .exs files (such as tests), they must be specified under `requireFiles`
