### ISSUE TITLE
ElixirLS - linked_list client: couldn't create connection to server.

### ISSUE THREAD

**Issue by Maxino22** [elixir-lsp/vscode-elixir-ls#339]
Hello, am new to elixir I installed the vs code Extension on my windows but i keep getting this error ... I installed Elixir and Erlang with choco 
I have added Elixir to path correctly iex work fine also mix ... the vscode extension thou will not connect to server 

This is the ouput of error on terminal
```
Starting ElixirLS release v0.14.6
Running in e:/Elixir/linked_list
** (Mix.Error) Could not find an SCM for dependency :sourceror from ElixirLS.LanguageServer.Mixfile
    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/dep/loader.ex:195: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.14.4) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/3
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.14.4) lib/mix/dep/loader.ex:358: Mix.Dep.Loader.mix_children/2
    (mix 1.14.4) lib/mix/dep/loader.ex:316: anonymous fn/4 in Mix.Dep.Loader.mix_dep/2
    (mix 1.14.4) lib/mix/project.ex:397: Mix.Project.in_project/4
[Error - 11:24:34 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 11:24:34 AM] Connection to server got closed. Server will restart.
true
[Error - 11:24:34 AM] ElixirLS - linked_list client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.6
Running in e:/Elixir/linked_list
** (Mix.Error) Could not find an SCM for dependency :sourceror from ElixirLS.LanguageServer.Mixfile
    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/dep/loader.ex:195: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.14.4) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/3
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.14.4) lib/mix/dep/loader.ex:358: Mix.Dep.Loader.mix_children/2
    (mix 1.14.4) lib/mix/dep/loader.ex:316: anonymous fn/4 in Mix.Dep.Loader.mix_dep/2
    (mix 1.14.4) lib/mix/project.ex:397: Mix.Project.in_project/4
[Error - 11:24:39 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 11:24:39 AM] Connection to server got closed. Server will restart.
true
[Error - 11:24:39 AM] ElixirLS - linked_list client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.6
Running in e:/Elixir/linked_list
** (Mix.Error) Could not find an SCM for dependency :sourceror from ElixirLS.LanguageServer.Mixfile
    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/dep/loader.ex:195: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.14.4) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/3
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.14.4) lib/mix/dep/loader.ex:358: Mix.Dep.Loader.mix_children/2
    (mix 1.14.4) lib/mix/dep/loader.ex:316: anonymous fn/4 in Mix.Dep.Loader.mix_dep/2
    (mix 1.14.4) lib/mix/project.ex:397: Mix.Project.in_project/4
[Error - 11:24:45 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 11:24:45 AM] Connection to server got closed. Server will restart.
true
[Error - 11:24:45 AM] ElixirLS - linked_list client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:24:45 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.6
Running in e:/Elixir/linked_list
** (Mix.Error) Could not find an SCM for dependency :sourceror from ElixirLS.LanguageServer.Mixfile
    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/dep/loader.ex:195: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.14.4) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/3
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.14.4) lib/mix/dep/loader.ex:358: Mix.Dep.Loader.mix_children/2
    (mix 1.14.4) lib/mix/dep/loader.ex:316: anonymous fn/4 in Mix.Dep.Loader.mix_dep/2
    (mix 1.14.4) lib/mix/project.ex:397: Mix.Project.in_project/4
[Error - 11:24:49 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 11:24:49 AM] Connection to server got closed. Server will restart.
true
[Error - 11:24:49 AM] ElixirLS - linked_list client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:24:49 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Starting ElixirLS release v0.14.6
Running in e:/Elixir/linked_list
** (Mix.Error) Could not find an SCM for dependency :sourceror from ElixirLS.LanguageServer.Mixfile
    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/dep/loader.ex:195: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.14.4) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/3
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.14.4) lib/mix/dep/loader.ex:358: Mix.Dep.Loader.mix_children/2
    (mix 1.14.4) lib/mix/dep/loader.ex:316: anonymous fn/4 in Mix.Dep.Loader.mix_dep/2
    (mix 1.14.4) lib/mix/project.ex:397: Mix.Project.in_project/4
[Error - 11:24:53 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:24:53 AM] The ElixirLS - linked_list server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 11:24:53 AM] ElixirLS - linked_list client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:24:53 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

**Comment by lukaszsamson** [comment]
Please try to remove `Mix.Utils.mix_cache()` directory

**Comment by Maxino22** [comment]
Did soo am still getting same error after restart

**Comment by jpacker** [comment]
I have the same issue, even after removing the mix cache directory.

**Comment by lukaszsamson** [comment]
@jpacker so your problem was missing hex installation? @Maxino22 do you have hex installed?

**Comment by Maxino22** [comment]
how do i install hex in windows

**Comment by lukaszsamson** [comment]
mix local.hex

**Comment by Maxino22** [comment]
Thanks, I installed  hex and it works fine
