### ISSUE TITLE
Elixir-ls not working in VSCode

### ISSUE THREAD

**Issue by dr1ver1** [elixir-lsp/vscode-elixir-ls#363]
### Is this the right repo?
I don't know

"If the language server fails to launch...". How do I check for this?
Code Completion isn't working. Debugging isn't working. The Test Explorer finds the test file but doesn't find the tests. I don't think the Dialyzer is running...

### Environment
**"Elixir: Copy ElixirLS Debug Info"**
* Elixir & Erlang versions (elixir --version): Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]

Elixir 1.15.3 (compiled with Erlang/OTP 26)

* VSCode ElixirLS version: 0.15.3
* Operating System Version: win32 10.0.22621

OS: Windows 11 Home

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
The only `.elixir_ls` folder I could find is `C:\Users\david\AppData\Local\mix\Cache\installs\elixir-1.15.3-erts-14.0.2\2b00f709b9297a1f57db8c75bf522678\deps\elixir_ls\apps\language_server\test\support\fixtures\.elixir_ls`
I have deleted it... so far it hasn't been re-created.

### Crash report template

- Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
```
Installing ElixirLS release v0.15.1
Running in c:/Users/david/Exercism/elixir/rational-numbers
Install complete
```
- Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.
```
log.ts:431  WARN [ms-vscode.remote-server]: The viewsWelcome contribution in 'ms-vscode.remote-server' requires 'enabledApiProposals: ["contribViewsWelcome"]' in order to use the 'group' proposed property.
console.ts:137 [Extension Host] ElixirLS: Loading extension
console.ts:137 [Extension Host] ElixirLS: activating extension in mode SINGLE_FOLDER
console.ts:137 [Extension Host] ElixirLS: Workspace folders are Array(1)
console.ts:137 [Extension Host] ElixirLS: Workspace is undefined
console.ts:137 [Extension Host] ElixirLS: creating test controller
console.ts:137 [Extension Host] ElixirLS: starting LSP client for c:\Users\david\Exercism\elixir\rational-numbers with server options Object client options Object
console.ts:137 [Extension Host] ElixirLS: extension activated
log.ts:421  INFO [perf] Render performance baseline is 23ms
console.ts:137 [Extension Host] ElixirLS: registering watcher in rational-numbers projectDir c:\Users\david\Exercism\elixir\rational-numbers
log.ts:441   ERR [Extension Host] Unhandled error in resolveHandler of test controller "elixirLSExUnitTests" TypeError: Cannot read properties of undefined (reading 'capabilities')
	at parseTestsInFileContents (c:\Users\david\.vscode\extensions\jakebecker.elixir-ls-0.15.3\out\testController.js:108:49)
	at controller.resolveHandler [as h] (c:\Users\david\.vscode\extensions\jakebecker.elixir-ls-0.15.3\out\testController.js:20:19)
	at a.I (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:17403)
	at a.expand (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:14203)
	at e.$w_b.$expandTest (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:5888)
	at t.N (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11199)
	at t.M (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:10965)
	at t.H (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:10046)
	at t.G (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:9122)
	at i.value (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:7952)
	at p.w (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
	at p.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2119)
	at f.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:13931)
	at i.value (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:30341)
	at p.w (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
	at p.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2119)
	at f.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:13931)
	at MessagePortMain.<anonymous> (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:28621)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
console.ts:137 [Extension Host] Unhandled error in resolveHandler of test controller "elixirLSExUnitTests" TypeError: Cannot read properties of undefined (reading 'capabilities')
	at parseTestsInFileContents (c:\Users\david\.vscode\extensions\jakebecker.elixir-ls-0.15.3\out\testController.js:108:49)
	at controller.resolveHandler [as h] (c:\Users\david\.vscode\extensions\jakebecker.elixir-ls-0.15.3\out\testController.js:20:19)
	at a.I (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:17403)
	at a.expand (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:14203)
	at e.$w_b.$expandTest (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:5888)
	at t.N (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11199)
	at t.M (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:10965)
	at t.H (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:10046)
	at t.G (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:9122)
	at i.value (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:7952)
	at p.w (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
	at p.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2119)
	at f.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:13931)
	at i.value (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:30341)
	at p.w (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
	at p.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2119)
	at f.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:13931)
	at MessagePortMain.<anonymous> (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:28621)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
v @ console.ts:137
```

**Comment by lukaszsamson** [comment]
OTP 26 is broken on windows. Please wait for patch release 26.0.3 or downgrade to 25. See https://github.com/elixir-lsp/elixir-ls/issues/886
