### ISSUE TITLE
ElixirLS does not working with a js error

### ISSUE THREAD

**Issue by tomwang57** [elixir-lsp/vscode-elixir-ls#434]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.2.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.15.6 (compiled with Erlang/OTP 24)

* VSCode ElixirLS version: 0.23.1
* Operating System Version: darwin 23.2.0

### Error message from output

```
[Error - 13:56:13] Request textDocument/documentSymbol failed.
TypeError: Cannot read properties of undefined (reading 'range')
	at rn (/Users/57block/.vscode/extensions/jakebecker.elixir-ls-0.23.1/out/extension.js:54:72599)
	at h (/Users/57block/.vscode/extensions/jakebecker.elixir-ls-0.23.1/out/extension.js:54:46807)
	at Object.ZF [as map] (/Users/57block/.vscode/extensions/jakebecker.elixir-ls-0.23.1/out/extension.js:54:46893)
	at Object.In [as asSymbolInformations] (/Users/57block/.vscode/extensions/jakebecker.elixir-ls-0.23.1/out/extension.js:54:72226)
	at E (/Users/57block/.vscode/extensions/jakebecker.elixir-ls-0.23.1/out/extension.js:58:56336)
	at runNextTicks (node:internal/process/task_queues:60:5)
	at process.processImmediate (node:internal/timers:449:9)
	at process.topLevelDomainCallback (node:domain:160:15)
	at process.callbackTrampoline (node:internal/async_hooks:128:24)
	at async d.provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:100486)
```

**Comment by lukaszsamson** [comment]
@tomwang57 please share a repro

**Comment by tomwang57** [comment]
> @tomwang57 please share a repro

I reinstalled the extension and it worked. Sorry to bother.
