### ISSUE TITLE
Docs for debugging?

### ISSUE THREAD

**Issue by CharlesIrvineKC** [elixir-lsp/vscode-elixir-ls#436]
Where do I find documentation for Elixir debugging in VS code using ElixirLS, especially debugging running tests? I see some pointers to vscode documentation, but these aren't helping much. Thanks

**Comment by CharlesIrvineKC** [comment]
I'm making a little progress. I can run tests. When I try to debug a test, I get the error below. Any hints on what I might need to do? I file where the error occurs is using custom macros that I've wrote.

```
11:46:57.864 [warning] Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Mozart.ProcessEngine is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead
    (elixir 1.16.2) lib/module.ex:2345: Module.assert_not_compiled!/3
    (elixir 1.16.2) lib/module.ex:1156: Module.defines?/2
    (elixir 1.16.2) lib/gen_server.ex:930: GenServer."MACRO-__before_compile__"/2
    (elixir_sense 2.0.0) lib/elixir_sense/core/normalized/macro/env.ex:68: anonymous fn/5 in ElixirSense.Core.Normalized.Macro.Env.wrap_expansion/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:1889: ElixirSense.Core.Compiler.expand_macro_callback/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:28: ElixirSense.Core.Compiler.expand/3
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:2126: ElixirSense.Core.Compiler.expand_block/5
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:103: ElixirSense.Core.Compiler.do_expand/3
```

**Comment by lukaszsamson** [comment]
Is it a log from LSP (output tab) or debug adapter (debug console tab)?

**Comment by CharlesIrvineKC** [comment]
From the debug console tab. Here is more context:

```

Interpreting module Mozart.ProcessEngineTest

11:46:57.864 [warning] Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Mozart.ProcessEngine is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead
    (elixir 1.16.2) lib/module.ex:2345: Module.assert_not_compiled!/3
    (elixir 1.16.2) lib/module.ex:1156: Module.defines?/2
    (elixir 1.16.2) lib/gen_server.ex:930: GenServer."MACRO-__before_compile__"/2
    (elixir_sense 2.0.0) lib/elixir_sense/core/normalized/macro/env.ex:68: anonymous fn/5 in ElixirSense.Core.Normalized.Macro.Env.wrap_expansion/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:1889: ElixirSense.Core.Compiler.expand_macro_callback/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:28: ElixirSense.Core.Compiler.expand/3
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:2126: ElixirSense.Core.Compiler.expand_block/5
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:103: ElixirSense.Core.Compiler.do_expand/3


11:46:57.934 [warning] Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Mozart.ProcessEngine is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead
    (elixir 1.16.2) lib/module.ex:2345: Module.assert_not_compiled!/3
    (elixir 1.16.2) lib/module.ex:1156: Module.defines?/2
    (elixir 1.16.2) lib/gen_server.ex:930: GenServer."MACRO-__before_compile__"/2
    (elixir_sense 2.0.0) lib/elixir_sense/core/normalized/macro/env.ex:68: anonymous fn/5 in ElixirSense.Core.Normalized.Macro.Env.wrap_expansion/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:1889: ElixirSense.Core.Compiler.expand_macro_callback/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:28: ElixirSense.Core.Compiler.expand/3
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:2126: ElixirSense.Core.Compiler.expand_block/5
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:103: ElixirSense.Core.Compiler.do_expand/3

Setting breakpoint in Mozart.ProcessEngine /Users/charlesirvine/src/mozart/lib/mozart/process_engine.ex:664

11:46:58.005 [warning] Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Mozart.ProcessEngine is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead
    (elixir 1.16.2) lib/module.ex:2345: Module.assert_not_compiled!/3
    (elixir 1.16.2) lib/module.ex:1156: Module.defines?/2
    (elixir 1.16.2) lib/gen_server.ex:930: GenServer."MACRO-__before_compile__"/2
    (elixir_sense 2.0.0) lib/elixir_sense/core/normalized/macro/env.ex:68: anonymous fn/5 in ElixirSense.Core.Normalized.Macro.Env.wrap_expansion/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:1889: ElixirSense.Core.Compiler.expand_macro_callback/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:28: ElixirSense.Core.Compiler.expand/3
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:2126: ElixirSense.Core.Compiler.expand_block/5
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:103: ElixirSense.Core.Compiler.do_expand/3



11:46:58.062 [warning] Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Mozart.ProcessEngine is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead
    (elixir 1.16.2) lib/module.ex:2345: Module.assert_not_compiled!/3
    (elixir 1.16.2) lib/module.ex:1156: Module.defines?/2
    (elixir 1.16.2) lib/gen_server.ex:930: GenServer."MACRO-__before_compile__"/2
    (elixir_sense 2.0.0) lib/elixir_sense/core/normalized/macro/env.ex:68: anonymous fn/5 in ElixirSense.Core.Normalized.Macro.Env.wrap_expansion/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:1889: ElixirSense.Core.Compiler.expand_macro_callback/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:28: ElixirSense.Core.Compiler.expand/3
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:2126: ElixirSense.Core.Compiler.expand_block/5
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:103: ElixirSense.Core.Compiler.do_expand/3

Running mix test --trace test/mozart/process_engine_test.exs:385 --formatter ElixirLS.DebugAdapter.ExUnitFormatter
[22m
11:46:58.296 [info] Process service initialized
[0m
39
[22m
11:46:58.577 [info] Start process instance [repeat conditional task][319912dd-81f6-4604-837c-76f4d9cccda6]
[0m
[22m
11:46:58.581 [info] New repeat task instance [repeat subprocess then conditional][a7b8adeb-aa73-4d37-857d-2154fb91a501]
[0m
[22m
11:46:58.583 [info] New service task instance [add 1 to count][b0873e99-9248-4e42-a34d-8886941b4a72]
[0m
Mix.Task.run returned:
:ok
Exiting debugger.
If this behavior is undesired consider setting `exitAfterTaskReturns` to `false` in launch config.

Mix task exited with reason
normal
returning code 0
Mix task exited with reason
normal
returning code 0
Received disconnect request

```

**Comment by CharlesIrvineKC** [comment]
Execution gets to the second breakpoint that I have set. At that point, the debugger exists with the following message:

```

Setting breakpoint in Mozart.ProcessEngine /Users/charlesirvine/src/mozart/lib/mozart/process_engine.ex:665

14:47:53.241 [warning] Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Mozart.ProcessEngine is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead
    (elixir 1.16.2) lib/module.ex:2345: Module.assert_not_compiled!/3
    (elixir 1.16.2) lib/module.ex:1156: Module.defines?/2
    (elixir 1.16.2) lib/gen_server.ex:930: GenServer."MACRO-__before_compile__"/2
    (elixir_sense 2.0.0) lib/elixir_sense/core/normalized/macro/env.ex:68: anonymous fn/5 in ElixirSense.Core.Normalized.Macro.Env.wrap_expansion/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:1889: ElixirSense.Core.Compiler.expand_macro_callback/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:28: ElixirSense.Core.Compiler.expand/3
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:2126: ElixirSense.Core.Compiler.expand_block/5
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:103: ElixirSense.Core.Compiler.do_expand/3


14:47:53.311 [warning] Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Mozart.ProcessEngine is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead
    (elixir 1.16.2) lib/module.ex:2345: Module.assert_not_compiled!/3
    (elixir 1.16.2) lib/module.ex:1156: Module.defines?/2
    (elixir 1.16.2) lib/gen_server.ex:930: GenServer."MACRO-__before_compile__"/2
    (elixir_sense 2.0.0) lib/elixir_sense/core/normalized/macro/env.ex:68: anonymous fn/5 in ElixirSense.Core.Normalized.Macro.Env.wrap_expansion/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:1889: ElixirSense.Core.Compiler.expand_macro_callback/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:28: ElixirSense.Core.Compiler.expand/3
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:2126: ElixirSense.Core.Compiler.expand_block/5
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:103: ElixirSense.Core.Compiler.do_expand/3

Running mix test --trace test/mozart/process_engine_test.exs:385 --formatter ElixirLS.DebugAdapter.ExUnitFormatter
[22m
14:47:53.570 [info] Process service initialized
[0m
39
[22m
14:48:14.041 [info] Start process instance [repeat conditional task][6286ec93-98e3-460b-82bd-43fc9d6575a0]
[0m
[22m
14:48:14.045 [info] New repeat task instance [repeat subprocess then conditional][ed28471a-d2c3-45f4-8c47-00e63407118c]
[0m
[22m
14:48:14.048 [info] New service task instance [add 1 to count][9941e5a6-454c-482f-83b2-6794a0498a16]
[0m
Mix.Task.run returned:
:ok
Exiting debugger.
If this behavior is undesired consider setting `exitAfterTaskReturns` to `false` in launch config.
Mix task exited with reason
normal
returning code 0
Mix task exited with reason
normal
returning code 0
Received disconnect request
Paused process #PID<0.743.0> exited with reason shutdown
```

**Comment by lukaszsamson** [comment]
Does it work when you run the test from the console? It looks like `mix test` task returns and debug session ends. Does your test crash the ex_unit process?

**Comment by CharlesIrvineKC** [comment]
The test runs fine from my mac terminal window. It also runs fine from vscode if I just run the test instead of debugging it.

**Comment by CharlesIrvineKC** [comment]
I figured it out. My test was spawning a process that the breakpoint was in.

**Comment by CharlesIrvineKC** [comment]
FYI - The debugger is working very well for me. I do see a lot of the warnings below though. What are the warnings telling me and might there be a way for me to "turn them off" so to speak? Thanks!!

```
14:47:53.311 [warning] Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Mozart.ProcessEngine is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead
    (elixir 1.16.2) lib/module.ex:2345: Module.assert_not_compiled!/3
    (elixir 1.16.2) lib/module.ex:1156: Module.defines?/2
    (elixir 1.16.2) lib/gen_server.ex:930: GenServer."MACRO-__before_compile__"/2
    (elixir_sense 2.0.0) lib/elixir_sense/core/normalized/macro/env.ex:68: anonymous fn/5 in ElixirSense.Core.Normalized.Macro.Env.wrap_expansion/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:1889: ElixirSense.Core.Compiler.expand_macro_callback/7
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:28: ElixirSense.Core.Compiler.expand/3
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:2126: ElixirSense.Core.Compiler.expand_block/5
    (elixir_sense 2.0.0) lib/elixir_sense/core/compiler.ex:103: ElixirSense.Core.Compiler.do_expand/3
```

**Comment by lukaszsamson** [comment]
> What are the warnings telling me and might there be a way for me to "turn them off" so to speak?

Those are harmless. It's the inference engine warning that it cannot fully analyze code
