### ISSUE TITLE
Extension will fail if the user shell outputs anything on startup

### ISSUE THREAD

**Issue by maxmuen** [elixir-lsp/vscode-elixir-ls#443]
It is possible to break the extension by echoing any text on shell startup. 

Example output:
```
Running /home/maxmuen/.vscode/extensions/jakebecker.elixir-ls-0.24.2/elixir-ls-release/launch.sh
Preferred shell is fish, launching launch.fish
Looking for ASDF install
ASDF install found in /home/maxmuen/.asdf/asdf.fish, sourcing
Installing ElixirLS release v0.24.1
Running in /home/maxmuen/sauce/day_one
Install complete
[Error - 5:13:32 PM] Client ElixirLS - day_one: connection to server is erroring.
Header must provide a Content-Length property.
{"lets break elixir vc\ncontent-length":"103"}
Shutting down server.
[Error - 5:13:32 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at fb.shutdown (/home/maxmuen/.vscode/extensions/jakebecker.elixir-ls-0.24.2/out/extension.js:41:8499)
	at fb.stop (/home/maxmuen/.vscode/extensions/jakebecker.elixir-ls-0.24.2/out/extension.js:41:8078)
	at fb.stop (/home/maxmuen/.vscode/extensions/jakebecker.elixir-ls-0.24.2/out/extension.js:44:30679)
	at fb.handleConnectionError (/home/maxmuen/.vscode/extensions/jakebecker.elixir-ls-0.24.2/out/extension.js:43:63)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

i am able to reproduce the error by using fish as a shell and having a `~/.config/fish/conf.d/evil.fish` file with the following content
```fish
echo lets break elixir vc
```

**Comment by maxmuen** [comment]
this might be related to #399
